package controllers

const COOKIE_WX_OPENID = "wx_openid"
const COOKIE_CITY = "city"
const CITY_ALL = "全部"
const PY_ALL = "all"
const CITY_QA = "庆安县"
const PY_QA = "qinganxian"
const CITY_SH = "绥化市"
const PY_SH = "suihuashi"
const CITY_BL = "北林市"
const PY_BL = "beilinshi"
const CITY_AD = "安达市"
const PY_AD = "andashi"
const CITY_SD = "肇东市"
const PY_SD = "zhaodongshi"
const CITY_HL = "海伦市"
const PY_HL = "hailunshu"
const CITY_WK = "望奎市"
const PY_WK = "wangkuishi"
const CITY_LX = "兰西县"
const PY_LX = "lanxixian"
const CITY_QG = "青冈县"
const PY_QG = "qinggangxian"
const CITY_MS = "明水县"
const PY_MS = "mingshuixian"
const CITY_SL = "绥棱县"
const PY_SL = "suilingxian"
